name: OKIEFARMHOUSE
favicon: null
layout_spectrum: 0.07734328950755298
typography_spectrum: 0.4602302743587643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7939587263390422
  lightness: 0.9605929832905531
  saturation: 0.5938763420563191
  rhythmicContrast: 0.7777072216849774
purpose: []
